### ISSUE TITLE
Change Version Number from TYPO3_8-7 to 2.0.3 for using in composer

### ISSUE THREAD

**Issue by mschmitz89** [jokumer/TYPO3-xfilelist#3]
First, thank you very much for your extension. It works pretty well.

Is there a possibilty to change the version number from TYPO3_8-7 to 2.0.3, so it is possible to install the latest version via composer?

All the best

**Comment by jokumer** [comment]
Sorry, have now pushed TAG 2.0.3 https://github.com/jokumer/TYPO3-xfilelist/tree/2.0.3

**Comment by mschmitz89** [comment]
Thanks! :)
