### ISSUE TITLE
Duplicate results if there is a match in the filename and it's metadata

### ISSUE THREAD

**Issue by timkarliczek3pc** [jokumer/TYPO3-xfilelist#4]

**Comment by jokumer** [comment]
Thx for the hint. Latest version?

**Comment by timkarliczek3pc** [comment]
Yes, latest version.
Please have a look at my simple fix for this issue.

**Comment by jokumer** [comment]
Merged into branches for TYPO3 7 and 8. Thanks for the bugfix @timkarliczek3pc
