### ISSUE TITLE
TYPO3 7.6 with empty allowed property in TCA

### ISSUE THREAD

**Issue by christophlehmann** [jokumer/TYPO3-xfilelist#6]
Hi,

The direct_mail extension has a field:

```
        'attachment' => array(
            'label' => 'LLL:EXT:direct_mail/Resources/Private/Language/locallang_tca.xlf:sys_dmail.attachment',
            'config' => array(
                'type' => 'group',
                'internal_type' => 'file',
                'allowed' => '', // Must be empty for disallowed to work.
                'disallowed' => 'php,php3',
                'max_size' => '10000',
                'uploadfolder' => 'uploads/tx_directmail',
                'show_thumbs' => '0',
                'size' => '3',
                'maxitems' => '5',
                'minitems' => '0'
            )
        ),
```

As of https://docs.typo3.org/typo3cms/TCAReference/7.6/Reference/Columns/Group/Index.html#disallowed the allowed/disallowed properties are set correctly.

Actually no files are selectable from filebrowser

**Comment by jokumer** [comment]
Thanks for the hint. Is it same behavior without EXT:xfilelist? Which version of TYPO3 you use?

**Comment by christophlehmann** [comment]
We use the latest 7.6 and your 7.6 branch. Without your ext it works as expected

**Comment by jokumer** [comment]
Will have a look at it.

**Comment by jokumer** [comment]
Fixed. Please install latest TYPO3_7-6 branch, version 1.1.1 to solve this behavior in your environment.

**Comment by christophlehmann** [comment]
Thank you very much!
