### ISSUE TITLE
Possible to search within Filelist module?

### ISSUE THREAD

**Issue by cgpro** [jokumer/TYPO3-xfilelist#7]
Hi,

I can search within content elements, but not in the Filelist module itself. (TYPO3 9.5). (I've added the db column "keywords" in the list)

Is there a configuration option to enable the search feature within the Filelist module?

I played a bit with the search within content elements and now I get the following error after submitting the search form (within a content element):

`
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1317178604: No file found for given UID: 6074 | TYPO3\CMS\Core\Resource\Exception\FileDoesNotExistException thrown in file /var/www/...project.../typo3/public/typo3/sysext/core/Classes/Resource/ResourceFactory.php in line 383. Requested URL: http://project.dev/typo3/index.php?route=%%2Fwizard%%2Frecord%%2Fbrowse&token=--AnonymizedToken--&mode=file&expandFolder=1%%3A%%2F&bparams=%%7C%%7C%%7Cpng%%2C%%20jpg%%2C%%20webp%%7Cdata-1-tt_content-1505-tx_valifycontentelements_image-sys_file_reference%%7Cinline.checkUniqueElement%%7C%%7Cinline.importElement
`

**Comment by jokumer** [comment]
1. Search within meta data in Filelist module
Accepted. TYPO3 Core did self implement search within meta data. This should be extendable within this extension. Sorry.
2. Error
I think, you have a missing file. Try following SQL query to search for your file
`
SELECT sf.uid AS FileUid,
	sf.identifier AS FileIdentifier,
    sf.missing AS FileMissing,
    sfr.uid AS FileReferenceUid,
    sfr.pid AS FileReferencePid
FROM sys_file sf
LEFT JOIN sys_file_reference sfr
	ON sfr.uid_local = sf.uid
WHERE sfr.tablenames = 'tt_content'
	AND sfr.uid_foreign = 1505
`

**Comment by cgpro** [comment]
Thanks for your quick response!

1. Is there a way to display search results within the core? I noticed, that only the file name will be searched, but not the meta data. Do you have plans to extend/update xfilelist?
2. Thanks for the hint, I'll try the query.

**Comment by jokumer** [comment]
1. I tried, and think the filelist module is searching in meta data. But don't know which fields currently. I have no plans, to work on xfilelist, since it is rarely used. PullRequest are welcome.

**Comment by cgpro** [comment]
Ok, thanks for your efforts! :-)
